#!/usr/bin/env tsx
/**
 * Appends cross-locale slug aliases to out/_redirects, after `next build`.
 *
 * Every post and concept ships a different slug per locale, so half of all
 * possible "locale prefix + slug" combinations are 404s that look completely
 * plausible from the outside. That is not hypothetical: the 404 log caught a
 * request for /tr/blog/google-search-profile-handle-swapping — the *English*
 * slug under the Turkish prefix, for an article that exists in both languages.
 *
 * The locale prefix is the deliberate part of such a URL and the slug is the
 * copied part, so each alias keeps the requested locale and swaps the slug for
 * that locale's real one. The reader lands on the article they asked for, in
 * the language they asked for, and hreflang still offers the other one.
 *
 * Generated rather than hand-listed because the set grows with every published
 * article — a rule you have to remember to add is a rule that rots.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { locales, type Locale } from "../lib/i18n";
import { getDictionary } from "../lib/dictionaries";
import { posts } from "../content/posts";
import { concepts } from "../content/concepts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const REDIRECTS = join(root, "out", "_redirects");
const MARKER = "# --- generated by scripts/route-aliases.ts";

interface Aliasable {
  locales: Record<Locale, { slug: string }>;
}

/**
 * `/{locale}/{section}/{slug from the other locale}` → the same article at the
 * slug that locale actually serves. Pairs whose slugs happen to match are
 * skipped: the rule would be a redirect loop onto itself.
 */
function aliases(items: readonly Aliasable[], section: (l: Locale) => string) {
  const rules: string[] = [];

  for (const item of items) {
    for (const locale of locales) {
      const real = item.locales[locale].slug;
      for (const other of locales) {
        const wrong = item.locales[other].slug;
        if (wrong === real) continue;
        rules.push(
          `/${locale}/${section(locale)}/${wrong}  /${locale}/${section(locale)}/${real}  301`,
        );
      }
    }
  }

  return rules;
}

if (!existsSync(REDIRECTS)) {
  throw new Error(
    `route-aliases: ${REDIRECTS} not found — run this after \`next build\`.`,
  );
}

const rules = [
  ...aliases(posts, (l) => getDictionary(l).routes.blog),
  ...aliases(concepts, (l) => getDictionary(l).routes.concepts),
];

// Pages caps a project at 2100 static rules and fails the whole deploy on the
// 2101st — better to hear about it here than from a red deployment.
const handWritten = readFileSync(REDIRECTS, "utf8")
  .split(MARKER)[0]
  .split("\n")
  .filter((line) => line.trim() && !line.trim().startsWith("#")).length;

if (handWritten + rules.length > 2000) {
  throw new Error(
    `route-aliases: ${handWritten + rules.length} redirect rules exceeds the ` +
      "safe margin under Cloudflare Pages' 2100 limit.",
  );
}

const body = [
  readFileSync(REDIRECTS, "utf8").split(MARKER)[0].trimEnd(),
  "",
  `${MARKER} — do not hand-edit ---`,
  "# Cross-locale slug aliases: the other language's slug under this language's",
  "# prefix, 301'd to the slug this locale actually serves.",
  ...rules,
  "",
].join("\n");

writeFileSync(REDIRECTS, body);
console.log(`route-aliases: appended ${rules.length} cross-locale aliases`);
