import type { Concept } from "@/lib/concepts";

export const geo: Concept = {
  id: "geo",
  category: "seo-geo",
  publishedAt: "2026-07-28",
  related: ["seo"],
  postIds: ["geo-rehberi"],
  locales: {
    tr: {
      slug: "geo",
      name: "GEO (Generative Engine Optimization)",
      graphLabel: "GEO",
      metaTitle: "GEO Nedir? Üretken Motor Optimizasyonu | Soleach Kavramlar",
      metaDescription:
        "GEO (üretken motor optimizasyonu) nedir? Markanın ChatGPT, Perplexity ve Google'ın yapay zekâ özetlerinde doğru anılmasını hedefleyen disiplinin tanımı.",
      shortDef:
        "Markanın ChatGPT, Perplexity ve Google'ın yapay zekâ özetleri gibi üretken motorların yanıtlarında doğru, güncel ve olumlu şekilde anılmasını hedefleyen optimizasyon disiplini.",
      sections: [
        {
          h2: "GEO nedir?",
          blocks: [
            {
              type: "p",
              text: "GEO, 'Generative Engine Optimization' ifadesinin kısaltması. Klasik SEO bir arama sonucu listesinde üst sıraya çıkmayı hedefler; GEO ise kullanıcı yapay zekâya soru sorduğunda üretilen cevabın içinde yer almayı hedefler. Kullanıcı çoğu zaman hiçbir siteye tıklamaz — yapay zekânın yazdığı cevabı okur ve orada hangi markaların anıldığı yeni rekabet alanıdır.",
            },
            {
              type: "p",
              text: "Bu motorlar cevaplarını büyük ölçüde açık web'den taradıkları içerikten kurar. Markan hakkında web'de ne kadar net, tutarlı ve makine tarafından okunabilir bilgi varsa, senin hakkında doğru konuşma ihtimalleri o kadar artar. Bu yüzden GEO'nun temeli teknik bir numara değil; taranabilir, yapılandırılmış ve soruya doğrudan cevap veren içerik üretmektir.",
            },
          ],
        },
        {
          h2: "Kozmetik markaları için GEO neden önemli?",
          blocks: [
            {
              type: "p",
              text: "Kozmetikte ürün araştırması soru formatında ilerler: 'hassas cilde uygun güneş kremi hangisi', 'niasinamid ile retinol birlikte kullanılır mı'. Bu sorular artık yalnızca Google'a değil, ChatGPT ve Perplexity'ye de soruluyor. Yanıtın içinde anılmayan marka, o müşterinin karar anında hiç var olmamış demektir.",
            },
            {
              type: "ul",
              items: [
                "GEO, SEO'nun yerine geçmez; sağlam SEO taranabilirlik sağladığı için GEO'nun ön koşuludur.",
                "Ölçü birimi sayfa sıralaması değil, markanın yanıtlar içinde doğru bilgiyle anılma sıklığıdır.",
                "SSS blokları, net tanımlar ve tutarlı marka bilgisi bu motorların en kolay alıntıladığı formatlardır.",
              ],
            },
            {
              type: "p",
              text: "GEO'yu kozmetik markası için pratikte nasıl kuracağını adım adım [GEO rehberimizde](/tr/blog/geo-nedir-yapay-zeka-gorunurlugu-rehberi) anlattık; zeminini oluşturan çalışma için [SEO](/tr/kavramlar/seo) kavramına bakabilirsin.",
            },
          ],
        },
      ],
      faq: [
        {
          q: "GEO, SEO'nun yerini mi alıyor?",
          a: "Hayır. İkisi aynı zeminin iki katmanı: SEO sitenin taranabilir ve anlaşılır olmasını sağlar, GEO bu zemin üzerinde markanın yapay zekâ yanıtlarında doğru anılmasını hedefler. Taranamayan bir site yapay zekâ motorları için de görünmezdir.",
        },
        {
          q: "GEO çalışması pratikte neleri kapsar?",
          a: "Taranabilir ve hızlı bir site, schema.org işaretlemeleri, soruya doğrudan cevap veren içerik (SSS ve rehber formatı), tutarlı marka bilgisi ve üçüncü taraf kaynaklarda doğru anılma. Yani büyük bölümü zaten iyi içerik ve iyi teknik altyapıdır.",
        },
      ],
      tags: ["GEO", "Üretken motor optimizasyonu", "Yapay zekâ görünürlüğü", "AI arama"],
    },
    en: {
      slug: "generative-engine-optimization",
      name: "GEO (Generative Engine Optimization)",
      graphLabel: "GEO",
      metaTitle: "What Is GEO? Generative Engine Optimization | Soleach",
      metaDescription:
        "GEO (Generative Engine Optimization) explained: the AI-visibility discipline that gets your brand mentioned accurately in ChatGPT and Perplexity answers.",
      shortDef:
        "The discipline of making sure a brand is mentioned accurately, currently and favorably inside answers generated by ChatGPT, Perplexity, Google's AI summaries and other generative engines.",
      sections: [
        {
          h2: "What is GEO?",
          blocks: [
            {
              type: "p",
              text: "GEO stands for Generative Engine Optimization. Classic SEO aims for a top position in a list of search results; GEO aims to be part of the answer itself when a user asks an AI a question. The user often never clicks through to any site — they read the generated answer, and which brands appear inside it is the new competitive surface.",
            },
            {
              type: "p",
              text: "These engines build their answers largely from content they crawl on the open web. The clearer, more consistent and more machine-readable the information about your brand is, the more likely they are to describe you correctly. That is why the foundation of GEO is not a technical trick — it is crawlable, well-structured content that answers real questions directly.",
            },
          ],
        },
        {
          h2: "Why GEO matters for beauty brands",
          blocks: [
            {
              type: "p",
              text: "Beauty product research happens in question form: 'which sunscreen suits sensitive skin', 'can I combine niacinamide with retinol'. Those questions now go to ChatGPT and Perplexity as well as Google. A brand that is absent from the answer simply does not exist at that customer's decision moment.",
            },
            {
              type: "ul",
              items: [
                "GEO does not replace SEO; solid SEO provides the crawlability that GEO depends on.",
                "The unit of measurement is not page rank but how often — and how accurately — your brand appears inside generated answers.",
                "FAQ blocks, clear definitions and consistent brand facts are the formats these engines quote most easily.",
              ],
            },
            {
              type: "p",
              text: "Our [GEO guide](/en/blog/what-is-geo-generative-engine-optimization-guide) walks through how a cosmetics brand puts this into practice step by step; for the groundwork it rests on, see [SEO](/en/concepts/seo).",
            },
          ],
        },
      ],
      faq: [
        {
          q: "Does GEO replace SEO?",
          a: "No. They are two layers of the same ground: SEO keeps your site crawlable and understandable, and GEO builds on that so your brand is represented correctly in AI answers. A site that cannot be crawled is invisible to AI engines too.",
        },
        {
          q: "What does GEO work actually involve?",
          a: "A crawlable, fast site, schema.org markup, content that answers questions directly (FAQ and guide formats), consistent brand information, and accurate mentions on third-party sources. Most of it is simply good content and good technical hygiene.",
        },
      ],
      tags: ["GEO", "Generative engine optimization", "AI visibility", "AI search"],
    },
  },
};
